[theme]

# Primary accent for interactive elements
primaryColor = '#F46197'

# Background color for the main content area
backgroundColor = '#151515'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#5B5B5B'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
font = "sans serif"